project:
  type: website
  output-dir: _site

website:
  title: "CATER"
  site-url: "https://cater-network.com"
  description: "Centre for the Advancement of Technology Education Research"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true