project:
  type: website

website:
  title: "CATER"
  # Replace 'logo.png' with the actual filename of your updated logo
  # logo: logo.png
  # logo-alt: "CATER Logo: The Center for the Advancement of Technology Education Research"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About CATER"
        href: about.qmd

    right:
      - icon: github
        href: https://github.com/
      - text: "Contact"
        href: about.qmd # Can use a contact section on the about page
  page-footer:
    left: "© 2026 **CATER**"
    center: "Centre for the Advancement of Technology Education Research"
    

format:
  html:
    theme:
      - cosmo # The base theme
      - custom.scss # Your brand styling overrides
    toc: false
    nav-empty: true
    code-fold: true
    # Include Bootstrap Icons globally for card icons
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">